const customStylesGrids = {
  placeholder: () => ({
    fontFamily: 'Jost',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    color: '#1D1D1D',
    position: 'relative',
    top: '25%',
  }),
  container: () => ({
    fontFamily: 'Jost',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    color: '#8c8c8c',
    height: '40px',
    position: 'relative',
    background: '#FFFFFF',
    borderRadius: '10px',
    paddingLeft: '10px',
    width: '200px',
    paddingRight: '80px',
    border: 'none',
    zIndex: '12',
  }),
  dropdownIndicator: () => ({
    position: 'absolute',
    width: '12px',
    height: '8px',
    top: '30%',
    left: '85%',
  }),
  option: () => ({
    fontFamily: 'Jost',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    color: '#8C8C8C',
  }),
  input: () => ({
    display: 'none',
  }),
  control: () => ({
    border: 'none',
  }),
  menu: () => ({
    background: '#FFFFFF',
    borderRadius: '30px',
    paddingTop: '20px',
    paddingLeft: '20px',
    marginTop: '5px',
    width: '300px',
    paddingBottom: '18px',
    position: 'absolute',
    zIndex: '5',
    left: 0,
  }),
  menuList: () => ({
    paddingRight: '219px',
  }),
  singleValue: () => ({
    fontFamily: 'Jost',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: '16px',
    lineHeight: '24px',
    color: '#1D1D1D',
    position: 'relative',
    top: '25%',
    right: '-10%',
  }),
};

export default customStylesGrids;
